In [12]:
import numpy as np

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [14]:
#Addition
result = a + b 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [15]:
#Subtraction
result = a - b 
print(result)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [16]:
#Matrix Multiplication
result = np.matmul(a,b)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
#Transpose of the result Matrix
result = result.T

In [18]:
print(result)

[[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]]
